### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rickoco**
small branding related edits...

### CODE REVIEW

**Comment by ruspl-afed** [comment]
Great to see another contributor! 👍 
Build is passing, the only problem is ECA.

**Comment by rickoco** [comment]
> Great to see another contributor! 👍
> Build is passing, the only problem is ECA.

not sure why as I have Committer status on OpenHW projects.  @chrisguindon or @DBees can one of you look at this pls?

**Comment by ruspl-afed** [comment]
> 
> not sure why as I have Committer status on OpenHW projects. @chrisguindon or @DBees can one of you look at this pls?

@rickoco please verify that your Eclipse account knows your GitHub identifier

**Comment by chrisguindon** [comment]
The problem is not with @rickoco:
https://accounts.eclipse.org/legal/eca/validation/44299

Rick O’Connor (rickoco@****.org) did not include the "Signed-off-by footer" which is required for all commits made by a contributor.

**Pull request closed without merging**
